application: markovtweet
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /authorize
  script: main.py

- url: /oauth_callback
  script: main.py

- url: /generate
  script: main.py

- url: /post
  script: main.py

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: not_found.py
